apiVersion: keycloak.org/v1alpha1
kind: KeycloakClient
metadata:
  name: example-client
  labels:
    app: sso
    realm: 3scale
spec:
  realmSelector:
    matchExpressions:
      - key: realm
        operator: Exists
        values:
          - 3scale
    matchLabels:
      app: sso
  client:
    clientId: example-client
    secret: password123
    directAccessGrantsEnabled: true
    implicitFlowEnabled: false
    publicClient: false
    standardFlowEnabled: false
    serviceAccountsEnabled: true    