apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: run-script
spec:
  workspaces:
  - name: storage
    readOnly: false
  - name: truststore
    readOnly: false    
  params:
  - name: script
  steps:
  - name: run-script
    image: centos
    script: $(params.script) 