FROM gcr.io/cloud-builders/mvn@sha256:57523fc43394d6d9d2414ee8d1c85ed7a13460cbb268c3cd16d28cfb3859e641

ENV LANG='en_US.UTF-8' LANGUAGE='en_US:en'
# Install java and the run-java script
# Also set up permissions for user `1001`
USER root

RUN microdnf install curl wget tar ca-certificates gcc gcc-c++ glibc-devel libstdc++-devel libstdc++ zlib zlib-devel \
    && microdnf update \
    && microdnf clean all

WORKDIR /opt
RUN wget https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-20.0.0/graalvm-ce-java11-linux-amd64-20.0.0.tar.gz >/dev/null 2>&1
RUN tar zxvf graalvm-ce-java11-linux-amd64-20.0.0.tar.gz
ENV GRAALVM_HOME=/opt/graalvm-ce-java11-20.0.0
ENV PATH=$GRAALVM_HOME/bin:$M2_HOME/bin:$PATH
RUN gu install native-image
# RUN yum -y install gcc gcc-c++ glibc-devel libstdc++-devel libstdc++ zlib zlib-devel
RUN chown -R 1001:0 $HOME && chmod -R g+rw $HOME
USER 1001
