apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cars-serverless-dev-pipeline-pvc
  labels:
      app: cars-serverless
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
