apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cars-native-dev-pipeline-pvc
  labels:
      app: cars-native
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
