kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: connected-cars-staging
  namespace: 3scale
spec:
  host: cc-staging-3scale.apps.sno.openshiftlabs.net
  to:
    kind: Service
    name: apicast-staging
    weight: 100
  port:
    targetPort: gateway
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: connected-cars-production
  namespace: 3scale
spec:
  host: cc-3scale.apps.sno.openshiftlabs.net
  to:
    kind: Service
    name: apicast-production
    weight: 100
  port:
    targetPort: gateway
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None  