apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: spring-boot-prd-template
objects:

- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
    labels:
      app: ${APPLICATION_NAME}
      version: ${VERSION_LABEL}
    name: ${APPLICATION_NAME}-${VERSION_LABEL}
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: ${APPLICATION_NAME}
        deploymentconfig: ${APPLICATION_NAME}
    strategy:
      type: RollingUpdate
    template:
      metadata:
        annotations:
          sidecar.istio.io/inject: "true"
        labels:
          app: ${APPLICATION_NAME}
          deploymentconfig: ${APPLICATION_NAME}
          version: ${VERSION_LABEL}
      spec:
        containers:
          - env:
              - name: SPRING_PROFILES_ACTIVE
                value: "${SPRING_PROFILES_ACTIVE}"
            image: ${IMAGE_REPO}/${IMAGE_NAME}:${IMAGE_TAG}
            imagePullPolicy: Always
            ports:
            - containerPort: 8080
            name: ${APPLICATION_NAME}
            resources:
              limits:
                cpu: 200m
                memory: 512Mi
              requests:
                cpu: 10m
                memory: 256Mi
            livenessProbe:
              httpGet:
                path: /health
                port: 8080
                scheme: HTTP
              initialDelaySeconds: 20
              timeoutSeconds: 1
              periodSeconds: 10
              successThreshold: 1
              failureThreshold: 3
            readinessProbe:
              httpGet:
                path: /health
                port: 8080
                scheme: HTTP
              initialDelaySeconds: 20
              timeoutSeconds: 1
              periodSeconds: 10
              successThreshold: 1
              failureThreshold: 3
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            volumeMounts:
              - mountPath: /config
                name: ${APPLICATION_NAME}-config-vol
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        serviceAccount: ${SERVICEACCOUNT_NAME}
        serviceAccountName: ${SERVICEACCOUNT_NAME}
        terminationGracePeriodSeconds: 30
        volumes:
          - configMap:
              defaultMode: 420
              name: ${APPLICATION_NAME}-${SPRING_PROFILES_ACTIVE}-config
            name: ${APPLICATION_NAME}-config-vol

parameters:
  - description: The name for the application.
    name: APPLICATION_NAME
    required: true
    value: "inventory"
  - description: The name for the application image.
    name: IMAGE_REPO
    required: true
    value: "quay.io/justindav1s"    
  - description: The name for the application image.
    name: IMAGE_NAME
    required: true
    value: "basket"
  - description: The tag for the application image.
    name: IMAGE_TAG
    required: true
    value: "0.0.1-SNAPSHOT"
  - description: The Spring Active Profile.
    name: SPRING_PROFILES_ACTIVE
    required: true
    value: "prd"
  - description: The version label for the application.
    name: VERSION_LABEL
    value: "v1"
  - description: The ServiceAccount name.
    name: SERVICEACCOUNT_NAME
    required: true
    value: "inventory-prd-sa"

