
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: knative-serving-template
objects:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
    labels:
      app: ${APP_NAME}
    name: ${SERVICEACCOUNT_NAME}

- apiVersion: serving.knative.dev/v1
  kind: Service
  metadata:
    name: ${APP_NAME}
    labels:
      app: ${APP_NAME}  
  spec:
    template:
      spec:
        containerConcurrency: 0
        containers:
          - image: '${IMAGE_REPO}/${IMAGE_NAME}:${IMAGE_TAG}'
            name: ${APP_NAME}
            volumeMounts:
              - name: application-properties
                mountPath: /${CONTAINER_WORKING_DIR}/config          
              - name: truststore
                mountPath: /${CONTAINER_WORKING_DIR}/truststore   
            readinessProbe:
              successThreshold: 1
              tcpSocket:
                port: 0
            livenessProbe:
              failureThreshold: 3
              httpGet:
                path: /${CONTEXT}/health
                port: 0
                scheme: HTTP
              periodSeconds: 10
              successThreshold: 1
              timeoutSeconds: 1                
            resources: {}
        enableServiceLinks: false
        timeoutSeconds: 300
        serviceAccount: ${SERVICEACCOUNT_NAME}
        serviceAccountName: ${SERVICEACCOUNT_NAME}
        volumes:
          - name: application-properties
            secret:
              secretName: ${APP_NAME}-${PROFILE}-application-properties
          - name: truststore
            secret:
              secretName: ${APP_NAME}-${PROFILE}-kafka-truststore    
    traffic:
      - latestRevision: true
        percent: 100

parameters:
  - description: The name for the application.
    name: APP_NAME
    required: true
    value: "inventory"
  - description: The name for the application.
    name: CONTEXT
    required: true
    value: "inventory"    
  - description: The name for the application image.
    name: IMAGE_REPO
    required: true
    value: "quay.io/justindav1s"    
  - description: The name for the application image.
    name: IMAGE_NAME
    required: true
    value: "basket"
  - description: The tag for the application image.
    name: IMAGE_TAG
    required: true
    value: "0.0.1-SNAPSHOT"
  - description: The Spring Active Profile.
    name: PROFILE
    required: true
    value: "prd"
  - description: The version label for the application.
    name: VERSION_LABEL
    value: "v1"
  - description: The ServiceAccount name.
    name: SERVICEACCOUNT_NAME
    required: true
    value: "inventory-prd-sa"
  - description: The ServiceAccount name.
    name: CONTAINER_WORKING_DIR
    required: true
    value: "deployments"