apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: wc-dev-kafka-cluster
  namespace: labs-dev
spec:
  entityOperator:
    topicOperator: {}
    userOperator: {}
  kafka:
    config:
      default.replication.factor: 2
      min.insync.replicas: 2
      inter.broker.protocol.version: '3.0'
      log.message.format.version: '3.0'
      offsets.topic.replication.factor: 3
      transaction.state.log.min.isr: 2
      transaction.state.log.replication.factor: 3
    listeners:
      - name: plain
        port: 9092
        tls: false
        type: internal
      - name: tls
        port: 9093
        tls: true
        type: internal
      - authentication:
          type: scram-sha-512
        name: external
        port: 9094
        tls: true
        type: route
      - authentication:
          enablePlain: true
          type: tls
        name: mtls
        port: 9095
        tls: true
        type: route         
    replicas: 3
    storage:
      type: persistent-claim
      size: 10Gi
    version: 3.0.0
  zookeeper:
    replicas: 3
    storage:
      type: persistent-claim
      size: 1Gi
