apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  labels:
    strimzi.io/cluster: my-cluster
  name: scram-user
  namespace: kafka-cluster2
spec:
  authentication:
    type: scram-sha-512