apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-template
spec:
  workspaces:
  - name: source
  params:
    - name: APP_NAME
      type: string
    - name: IMAGE_REPO
      type: string
    - name: IMAGE_NAME
      type: string
    - name: IMAGE_TAG
      type: string
    - name: PROFILE
      type: string
    - name: VERSION_LABEL
      type: string
    - name: SERVICEACCOUNT_NAME
      type: string
  steps:
    - name: apply
      image: image-registry.openshift-image-registry.svc:5000/openshift/cli:latest
      workingDir: /workspace/source/$(params.APP_NAME)
      command: ["/bin/bash", "-c"]
      args:
        - |-
          echo -----------CLEANUP------------------------
          oc delete sa,deployment,service,route,configmap,secret -l app=$(params.APP_NAME)
          echo -----------DEPLOY------------------------

          oc new-app -f tekton/ocp-templates/ingress-template.yaml \
            -p APP_NAME=$(params.APP_NAME) \
            -p SERVICE_NAME=$(params.IMAGE_NAME) \
            -p SERVICEACCOUNT_NAME=$(params.SERVICEACCOUNT_NAME)

          oc secrets link $(params.SERVICEACCOUNT_NAME) quay-dockercfg --for=pull  
        
          oc create secret generic $(params.APP_NAME)-$(params.PROFILE)-application-properties \
              --from-file=src/main/resources/application.$(params.PROFILE).properties

          oc create secret generic $(params.APP_NAME)-$(params.PROFILE)-kafka-truststore \
              --from-file=../kafka-truststore.jks

          oc label configmap $(params.APP_NAME)-$(params.PROFILE)-application-properties app=$(params.APP_NAME)
          oc label configmap $(params.APP_NAME)-$(params.PROFILE)-kafka-truststore app=$(params.APP_NAME)

          oc new-app -f tekton/ocp-templates/deployment-template.yaml \
            -p APP_NAME=$(params.APP_NAME) \
            -p IMAGE_REPO=$(params.IMAGE_REPO) \
            -p IMAGE_NAME=$(params.IMAGE_NAME) \
            -p IMAGE_TAG=$(params.IMAGE_TAG) \
            -p PROFILE=$(params.PROFILE) \
            -p VERSION_LABEL=$(params.VERSION_LABEL) \
            -p SERVICEACCOUNT_NAME=$(params.SERVICEACCOUNT_NAME)
          echo -------------DONE-------------------