apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: quarkus-native-build
spec:
  workspaces:
    - name: shared-workspace
    - name: maven-settings
    - name: truststore
  params:
    - name: APP_NAME
      type: string
  steps:
    - name: apply
      image: quay.io/justindav1s/quarkus-native-builder:latest
      workingDir: /workspace/source/$(params.APP_NAME)
      command: ["/bin/bash", "-c"]
      args:
        - |-
          echo -----------Build------------------------
          chmod -R 777 *
          mvn -U -B '-DskipTests' '-Dnative'  '-Dquarkus.package.type=native' 'clean' 'package'
          echo -------------DONE-------------------