apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: quarkus-template
objects:

- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
    labels:
      app: ${APP_NAME}
      version: ${VERSION_LABEL}
    name: ${APP_NAME}-${VERSION_LABEL}
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: ${APP_NAME}
        deployment: ${APP_NAME}
    strategy:
      type: RollingUpdate
    template:
      metadata:
        annotations:
          sidecar.istio.io/inject: "true"
        labels:
          app: ${APP_NAME}
          deployment: ${APP_NAME}
          version: ${VERSION_LABEL}
      spec:
        containers:
          - env:
              - name: PROFILE
                value: "${PROFILE}"
            image: ${IMAGE_REPO}/${IMAGE_NAME}:${IMAGE_TAG}
            imagePullPolicy: Always
            ports:
            - containerPort: 8080
            name: ${APP_NAME}
            resources:
              limits:
                cpu: 200m
                memory: 512Mi
              requests:
                cpu: 10m
                memory: 256Mi
            livenessProbe:
              httpGet:
                path: /${APP_NAME}/health
                port: 8080
                scheme: HTTP
              initialDelaySeconds: 20
              timeoutSeconds: 1
              periodSeconds: 10
              successThreshold: 1
              failureThreshold: 3
            readinessProbe:
              httpGet:
                path: /${APP_NAME}/health
                port: 8080
                scheme: HTTP
              initialDelaySeconds: 20
              timeoutSeconds: 1
              periodSeconds: 10
              successThreshold: 1
              failureThreshold: 3
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            volumeMounts:
              - mountPath: /deployments/config
                name: ${APP_NAME}-${PROFILE}-application-properties
              - mountPath: /deployments/truststore
                name: ${APP_NAME}-${PROFILE}-kafka-truststore                
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        serviceAccount: ${SERVICEACCOUNT_NAME}
        serviceAccountName: ${SERVICEACCOUNT_NAME}
        terminationGracePeriodSeconds: 35
        volumes:
          - name: ${APP_NAME}-${PROFILE}-application-properties
            secret:
              secretName: ${APP_NAME}-${PROFILE}-application-properties
          - name: ${APP_NAME}-${PROFILE}-kafka-truststore
            secret:
              secretName: ${APP_NAME}-${PROFILE}-kafka-truststore

parameters:
  - description: The name for the application.
    name: APP_NAME
    required: true
    value: "inventory"
  - description: The name for the application image.
    name: IMAGE_REPO
    required: true
    value: "quay.io/justindav1s"    
  - description: The name for the application image.
    name: IMAGE_NAME
    required: true
    value: "basket"
  - description: The tag for the application image.
    name: IMAGE_TAG
    required: true
    value: "0.0.1-SNAPSHOT"
  - description: The Spring Active Profile.
    name: PROFILE
    required: true
    value: "prd"
  - description: The version label for the application.
    name: VERSION_LABEL
    value: "v1"
  - description: The ServiceAccount name.
    name: SERVICEACCOUNT_NAME
    required: true
    value: "inventory-prd-sa"

